# Generated by Django 6.0.1 on 2026-05-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristprofile',
            name='current_city',
        ),
    ]
