# Generated by Django 6.0.1 on 2026-05-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0002_remove_touristprofile_current_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longitude',
        ),
    ]
