# Generated by Django 6.0.1 on 2026-05-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0003_remove_post_latitude_remove_post_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSharePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_location_permissions', to=settings.AUTH_USER_MODEL)),
                ('granter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_location_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('granter', 'grantee')},
            },
        ),
    ]
