# Generated by Django 6.0.1 on 2026-05-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0004_locationsharepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last API activity, used to determine online status.', null=True),
        ),
    ]
